### ISSUE TITLE
Error exucute call-transcript-wazo

### ISSUE THREAD

**Issue by rahulkathet** [pc-m/transcript-demo#1]
Hi,
When I exucute call-transcript-wazo <channel uniqueid>
it gives me below error, I wasnt able to setup this can you help where I am doing wrong?

Traceback (most recent call last):
  File "/usr/local/bin/call-transcript-wazo", line 11, in <module>
    load_entry_point('transcript-demo==1.0', 'console_scripts', 'call-transcript-wazo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/transcript_demo-1.0-py2.7.egg/transcript_demo/wazo.py", line 9, in <module>
    from .transcription import Transcriber, LINEAR16
  File "/usr/local/lib/python2.7/dist-packages/transcript_demo-1.0-py2.7.egg/transcript_demo/transcription.py", line 6, in <module>
    from queue import Queue
ImportError: No module named queue

**Comment by jorgesisco** [comment]
you have to change Queue for queue, if you are using python3, a lot of things needs to be reformatted.
