### ISSUE TITLE
ModuleNotFoundError: No module named 'ari'`

### ISSUE THREAD

**Issue by abdulgig** [pc-m/transcript-demo#2]
@pc-m , throws an error ! Perhaps has to do with my env ? The install was clean though

root@fpbx:/usr/src/transcript-demo# call-transcript-ari-stasis

Upon running ```call-transcript-ari-stasis```
```
Traceback (most recent call last):
  File "/usr/local/bin/call-transcript-ari-stasis", line 11, in <module>
    load_entry_point('transcript-demo==1.0', 'console_scripts', 'call-transcript-ari-stasis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/transcript_demo-1.0-py3.7.egg/transcript_demo/ari_stasis.py", line 5, in <module>
    import ari
ModuleNotFoundError: No module named 'ari'
```

**Comment by Bunoviske** [comment]
the requirements.txt is incomplete. it should be liked this:

```
google-cloud-speech==1.3.4
ari
```
